---
-
  hosts: all

  tasks:
    - name: Print Hello
      debug:
        msg: "Hello there!"

    - name: Delete a file
      file:
        state: absent
        path: /LOG/A.log

    - name: "Read a file content"
      shell: |
        cat LOG/B.log
      register: file_content

    - name: "Print the file content to a console"
      debug:
        msg: "{{ file_content.stdout }}"
