---
- hosts: all
  tasks:
  - name: Ansible delete file glob
    find:
      paths: /root
      patterns: "*.log"
    register: files_to_delete
    become: yes
    become_method: su
  
  - name: Print log file names
    debug:
      msg: "{{ files_to_delete.files }}"
      
  - name: Ansible remove file glob
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_to_delete.files }}"
